acceleraterent/urls.py
# urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from aluguel_carros.views import HomeView, CustomLogoutView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('aluguel/', include('aluguel_carros.urls')),  # Adicione '/' no final para consistência
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aluguel_carros/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.

class Carro(models.Model):
    placa=models.CharField('Placa:', max_length=8, unique=True)
    modelo = models.CharField('Modelo:', max_length=100)
    ano =  models.CharField('Ano:', max_length=10)
    foto = models.ImageField('Foto:', upload_to='carros', blank=True, null=True)  
    disponivel = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.modelo} - {self.placa} - {self.ano} - {self.disponivel}"
   
    def esta_disponivel(self):
        return self.disponivel   

class Funcionario(models.Model):
    nomeFuncionario = models.CharField('Nome:', max_length=254)
    emailFuncionario = models.EmailField('Email:')
    cpfFuncionario = models.CharField('CPF:',max_length=11)
    cargo = models.CharField('Cargo:',max_length=100)
    telefoneFuncionario = models.CharField('Contato:',max_length=20, blank=True, null=True)
    
    
    def __str__(self):
       return f"{self.nomeFuncionario} - {self.cargo}"

class Cliente(models.Model):
    nomeCliente = models.CharField('Nome:', max_length=254)
    emailCliente = models.EmailField('Email:')
    cpfCliente = models.CharField('CPF:',max_length=11)
    telefoneCliente = models.CharField('Contato', max_length=20, blank=True, null=True)
    enderecoCliente = models.TextField('Endereço:')
    
    def __str__(self):
       return f"{self.nomeCliente} - {self.emailCliente}"

class ContratoAluguel(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data_inicio = models.DateField()
    data_fim = models.DateField()
    devolvido = models.BooleanField(default=False)

    def __str__(self):
       return f"{self.id} - {self.carro.modelo} - {self.cliente.nomeCliente} - {self.data_inicio} - {self.data_fim}"

class DevolucaoCarro(models.Model):
    contrato = models.OneToOneField('ContratoAluguel', on_delete=models.CASCADE)
    data_devolucao = models.DateField('Data de Devolução')
    descricao_avaria = models.TextField('Descrição da Avaria', blank=True, null=True)  
    def __str__(self):
        return f"Devolução para Contrato {self.contrato.id} em {self.data_devolucao}"
    

templates/carro/adicionar_carro.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Adcionar Carro{% endblock %}

{% block content %}


    <div class="container-fluir mb-5">
        <h2 class=" text-center text-white bg-success py-5">Adicionar Carro</h2>
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-success" type="submit">Adicionar Carro</button>
            </form> 
        </div>
    </div>
    
{% endblock %}

templates/carro/carro_confirm_delete.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Excluir Carro{% endblock %}

    {% block content %}
    <div class="container-fluir mb-5">
        <h2 class=" text-center text-white bg-success py-5">Excluir Carro</h2>
            <div class="container my-5">
                <h4>Tem certeza de que deseja excluir o carro "{{ carro.modelo }}"?</h4>
                <form method="post">{% csrf_token %}
                    <button class="btn btn-danger mt-5" type="submit">Confirmar Exclusão</button>
                </form>

            </div>

    </div>
    
        

   
{% endblock %}

templates/carro/detalhes_carro.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Detalhes do Carro{% endblock %}

{% block content %}
    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Detalhes do Carro</h2>
    </div>

    <div class="container mb-5 mx-2">
        {% if carro.foto %}
            <p><img src="{{ carro.foto.url }}" alt="{{ carro.modelo }}" width="400"></p>
        {% else %}
            <p>Sem foto disponível</p>
        {% endif %}
        <h4 class="container bg-primary-subtle">
            <p>Modelo: {{ carro.modelo }}</p>
            <p>Placa: {{ carro.placa }}</p>
            <p>Ano: {{ carro.ano }}</p>
            <p>Disponível: {% if carro.disponivel %}Sim{% else %}Não{% endif %}</p>
        </h4>

        <a class="btn btn-primary" href="{% url 'editar_carro' carro.id %}" role="button">Atualizar</a>

        <!-- Adicione um modal para confirmação da exclusão -->
        <a class="btn btn-danger" href="{% url 'excluir_carro' carro.id %}">Excluir Carro</a>
    </div>
{% endblock %}

templates/carro/editar_carro.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Atualizar Carro{% endblock %}

{% block content %}

    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Editar Carro</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Salvar Alterações</button>
        </form>
        
    </div>
        
    
{% endblock %}

templates/carro/listar_carros.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Listagem de Carros{% endblock %}

{% block content %}
{%bootstrap_messages%}
    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Listagem de Carros</h2>
    </div>

    <div class="container-fluid mb-5 mx-2">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Carro</th>
                    <th scope="col">Placa</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Ano</th>
                    <th scope="col">Disponibilidade</th>
                </tr>
            </thead>
            <tbody>
                {% for carro in carros %}
                    <tr>
                        <td>
                            {% if carro.foto %}
                                <a href="{% url 'detalhes_carro' carro.id %}">
                                    <img src="{{ carro.foto.url }}" alt="{{ carro.modelo }}" width="200">
                                </a>
                            {% endif %}
                        </td>
                        <td><a href="{% url 'detalhes_carro' carro.id %}">{{ carro.placa }}</a></td>
                        <td><a href="{% url 'detalhes_carro' carro.id %}">{{ carro.modelo }}</a></td>
                        <td><a href="{% url 'detalhes_carro' carro.id %}">{{ carro.ano }}</a></td>
                        <td><a href="{% url 'detalhes_carro' carro.id %}">{% if carro.disponivel %}Sim{% else %}Não{% endif %}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container-fluir">
        {% bootstrap_pagination page_obj %}
        {% if perms.carro.add_carro %}
        <a class="btn btn-success mx-2" href="{% url 'adicionar_carro' %}" role="button">Cadastrar carro</a>
    {% endif %}
    </div>
    
{% endblock %}