acceleraterent/urls.py
# urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from aluguel_carros.views import HomeView, CustomLogoutView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('aluguel/', include('aluguel_carros.urls')),  # Adicione '/' no final para consistência
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aluguel_carros/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.

class Carro(models.Model):
    placa=models.CharField('Placa:', max_length=8, unique=True)
    modelo = models.CharField('Modelo:', max_length=100)
    ano =  models.CharField('Ano:', max_length=10)
    foto = models.ImageField('Foto:', upload_to='carros', blank=True, null=True)  
    disponivel = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.modelo} - {self.placa} - {self.ano} - {self.disponivel}"
   
    def esta_disponivel(self):
        return self.disponivel   

class Funcionario(models.Model):
    nomeFuncionario = models.CharField('Nome:', max_length=254)
    emailFuncionario = models.EmailField('Email:')
    cpfFuncionario = models.CharField('CPF:',max_length=11)
    cargo = models.CharField('Cargo:',max_length=100)
    telefoneFuncionario = models.CharField('Contato:',max_length=20, blank=True, null=True)
    
    
    def __str__(self):
       return f"{self.nomeFuncionario} - {self.cargo}"

class Cliente(models.Model):
    nomeCliente = models.CharField('Nome:', max_length=254)
    emailCliente = models.EmailField('Email:')
    cpfCliente = models.CharField('CPF:',max_length=11)
    telefoneCliente = models.CharField('Contato', max_length=20, blank=True, null=True)
    enderecoCliente = models.TextField('Endereço:')
    
    def __str__(self):
       return f"{self.nomeCliente} - {self.emailCliente}"

class ContratoAluguel(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data_inicio = models.DateField()
    data_fim = models.DateField()
    devolvido = models.BooleanField(default=False)

    def __str__(self):
       return f"{self.id} - {self.carro.modelo} - {self.cliente.nomeCliente} - {self.data_inicio} - {self.data_fim}"

class DevolucaoCarro(models.Model):
    contrato = models.OneToOneField('ContratoAluguel', on_delete=models.CASCADE)
    data_devolucao = models.DateField('Data de Devolução')
    descricao_avaria = models.TextField('Descrição da Avaria', blank=True, null=True)  
    def __str__(self):
        return f"Devolução para Contrato {self.contrato.id} em {self.data_devolucao}"
    

templates/cliente/adicionar_cliente.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Adcionar Cliente{% endblock %}

{% block content %}


    <div class="container-fluir mb-5">
        <h2 class=" text-center text-white bg-success py-5">Adicionar Clientes</h2>
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-success" type="submit">Adicionar Cliente</button>
            </form> 
        </div>
    </div>
    
{% endblock %}

templates/cliente/cliente_confirm_delete.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Excluir Cliente{% endblock %}

    {% block content %}
    <div class="container-fluir mb-5">
        <h2 class=" text-center text-white bg-success py-5">Excluir Cliente</h2>
            <div class="container my-5">
                <h4>Tem certeza de que deseja excluir o cliente "{{ cliente.nomeCliente }}"?</h4>
                <form method="post">{% csrf_token %}
                    <button class="btn btn-danger mt-5" type="submit">Confirmar Exclusão</button>
                </form>

            </div>

    </div>
    
        

   
{% endblock %}

templates/cliente/detalhes_cliente.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Cliente{% endblock %}

{% block content %}
    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Cliente</h2>
    </div>

    <div class="container mb-5 mx-2">
        
        <h4 class="container bg-primary-subtle">
            <p>Nome: {{ cliente.nomeCliente }}</p>
            <p>Email: {{ cliente.emailCliente }}</p>
            <p>CPF: {{ cliente.cpfCliente }}</p>
            <p>Contato: {{ cliente.telefoneCliente }}</p>
            <p>Endereço: {{ cliente.enderecoCliente }}</p>
        </h4>

        <a class="btn btn-primary" href="{% url 'editar_cliente' cliente.id %}" role="button">Atualizar</a>

        <!-- Adicione um modal para confirmação da exclusão -->
        <a class="btn btn-danger" href="{% url 'excluir_cliente' cliente.id %}">Excluir Cliente</a>
    </div>
{% endblock %}

templates/cliente/editar_cliente.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Atualizar Cliente{% endblock %}

{% block content %}

    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Editar Cliente</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Salvar Alterações</button>
        </form>
        
    </div>
        
    
{% endblock %}

templates/cliente/listar_clientes.html
{% extends 'base.html' %}
{% load static bootstrap5 %}

{% block title %}Listagem de Clientes{% endblock %}

{% block content %}
{%bootstrap_messages%}
    <div class="container-fluid mb-5">
        <h2 class="text-center text-white bg-success py-5">Listagem de Clientes</h2>
    </div>

    <div class="container-fluid mb-5 mx-2">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Contato</th>
                    <th scope="col">Endeereço</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                    <tr>
                        <td><a href="{% url 'detalhes_cliente' cliente.id %}">{{ cliente.nomeCliente }}</a></td>
                        <td><a href="{% url 'detalhes_cliente' cliente.id %}">{{ cliente.emailCliente }}</a></td>
                        <td><a href="{% url 'detalhes_cliente' cliente.id %}">{{ cliente.cpfCliente }}</a></td>
                        <td><a href="{% url 'detalhes_cliente' cliente.id %}">{{ cliente.telefoneCliente }}</a></td>
                        <td><a href="{% url 'detalhes_cliente' cliente.id %}">{{ cliente.enderecoCliente }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container-fluir">
        {% bootstrap_pagination page_obj %}
        {% if perms.cliente.add_cliente %}
        <a class="btn btn-success mx-2" href="{% url 'adicionar_cliente' %}" role="button">Cadastrar Cliente</a>
    {% endif %}
    </div>
    
{% endblock %}